language: python

jobs:
  include:
    # perform a linux build
    - services: docker
    # and a mac build
    - os: osx
      language: shell
    # and a windows build
    - os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BUILD="cp36-* cp37-* cp38-*"
    - CIBW_BEFORE_BUILD="pip install -r requirements_dev.txt"

install:
  - |
    if  [[ "${TRAVIS_OS_NAME:-}" == "windows" ]]; then
      python -m pip install cibuildwheel==1.4.2
    else
      python3 -m pip install cibuildwheel==1.4.2
    fi

script:
  - |
    if  [[ "${TRAVIS_OS_NAME:-}" == "windows" ]]; then
      python -m cibuildwheel --output-dir wheelhouse
    else
      python3 -m cibuildwheel --output-dir wheelhouse
    fi

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    python3 -m pip install twine
    python3 -m twine upload --repository testpypi wheelhouse/*.whl
    if [[ $TRAVIS_TAG ]]; then
      TWINE_PASSWORD=$TWINE_PASSWORD_PYPI
      python3 -m twine upload wheelhouse/*.whl
    fi
