language: python

jobs:
  include:
    # perform a linux build
    - services: docker
      env: PYTHON="python3"
    # and a mac build
    - os: osx
      language: shell
      env: PYTHON="python3"
    # and a windows build
    - os: windows
      language: shell
      env: PYTHON="python"
      before_install:
        - choco install python --version 3.8.0
        - export PATH="/c/Python38:/c/Python38/Scripts:$PATH"

env:
  global:
    - TWINE_USERNAME=__token__
    - CIBW_BUILD="cp36-* cp37-* cp38-*"
    - CIBW_BEFORE_BUILD="pip install -r requirements_dev.txt"

install:
  - $PYTHON -m pip install cibuildwheel==1.4.2

script:
  - $PYTHON -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    python3 -m pip install twine
    python3 -m twine upload --repository testpypi wheelhouse/*.whl
    if [[ $TRAVIS_TAG ]]; then
      TWINE_PASSWORD=$TWINE_PASSWORD_PYPI
      python3 -m twine upload wheelhouse/*.whl
    fi
