notifications:
  email: false
matrix:
  include:
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64 PLAT=manylinux1_x86_64
    language: python
    python:
    - "3.8"  
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux1_i686 PRE_CMD=linux32 PLAT=manylinux1_i686
    language: python
    python:
    - "3.8"  
  - sudo: required
    services:
    - docker
    env: DOCKER_IMAGE=quay.io/pypa/manylinux2010_x86_64 PLAT=manylinux2010_x86_64
    language: python
    python:
    - "3.8"  

env:
  global:
    - TWINE_USERNAME=__token__

install:
- docker pull $DOCKER_IMAGE

script:
- docker run --rm -e PLAT=$PLAT -v `pwd`:/io $DOCKER_IMAGE $PRE_CMD /io/travis/build-wheels.sh

after_success:
  # if the release was tagged, upload them to PyPI
  - |
    python3 -m pip install twine
    python3 -m twine upload --repository testpypi wheelhouse/*.whl
    if [[ $TRAVIS_TAG ]]; then
      TWINE_PASSWORD = $TWINE_PASSWORD_PYPI
      python3 -m twine upload wheelhouse/*.whl
    fi
